# Introduction to NumPy
### By **[NimbleBox](https://www.nimblebox.ai)**

[<img src="./assets/nbx.jpeg" alt="NimbleBox.ai logo" width="600"/>](https://www.nimblebox.ai)

Parts of this notebook are from Data-X: Introduction to Numpy tutorial by [Alexander Fred Ojala](https://alex.fo/) and [Ikhlaq Sidhu](https://vcresearch.berkeley.edu/faculty/ikhlaq-sidhu),  [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by [Jake VanderPlas](https://github.com/jakevdp/PythonDataScienceHandbook) and [NumPy Documentation](https://numpy.org/doc/1.17/index.html).

## Introduction:  

NumPy stands for **Numerical Python** and it is the fundamental package for scientific computing in Python. It is a package that lets you efficiently store and manipulate numerical arrays. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities


In this tutorial, we will cover:

* **Basics**: Different ways to create NumPy Arrays and Basics of NumPy
* **Computation**: Computations on NumPy arrays using Universal Functions and other NumPy Routines
* **Aggregations**: Various function used to aggregate for NumPy arrays

### NumPy contains an array object that is "fast"


<img src="https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/threefundamental.png">


**It stores / consists of**:
* location of a memory block (allocated all at one time)
* a shape (3 x 3 or 1 x 9, etc)
* data type / size of each element

The core feauture that NumPy supports is its multi-dimensional arrays. In NumPy, dimensions are called axes and the number of axes is called a rank.

### NumPy Array Anotomy
<img src= "https://github.com/ikhlaqsidhu/data-x/raw/master/imgsource/anatomyarray.png">


We'll start with the standard NumPy import, under the alias `np`

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.17.4


### Basics of NumPy Array

#### 1. Creating a NumPy Array

##### From Python List

We use `np.array` to create a numpy array object from python list.

In [3]:
# Create array from Python list
list1 = [1, 2, 3, 4]
data = np.array(list1)
print(data)

[1 2 3 4]


In [4]:
# Find out object type
print(type(list1))
print(type(data))

<class 'list'>
<class 'numpy.ndarray'>


Python being a dynamically typed language, Python lists can contain elements with hetarogenous data-types. But NumPy is constrained to array with which have homogenous data-types. If the data types are not homogenous, NumPy will upcast (if possible) to the most logical data type

In [5]:
# NumPy converts to most logical data type
data1 = np.array([1.2, 2, 3, 4])
print(data1)
print(data1.dtype) # all values will be converted to floats

[1.2 2.  3.  4. ]
float64


In [6]:
# Here if we store a float in an int array, the float will be up-casted to an int
list2 = [1, 2, 3, 4]
data2 = np.array(list2)
data2[0] = 3.14159
print(data2)

[3 2 3 4]


In [7]:
# We can manually specify the datatype
data3 = np.array([1, 2, 3], dtype="str")
print(data3)
print(data3.dtype)

['1' '2' '3']
<U1


In order to perform any mathematical operations on NumPy arrays, all the elements must be of a type that is valid to perform these mathematical operations.

In [8]:
#This will give you a TypeError
'''
a = np.random.normal(0,1,1000)
b = np.arange(1000, dtype=np.int8)
c = np.arange(1000, dtype=np.int16)
c += a + b
print(c)
'''

'\na = np.random.normal(0,1,1000)\nb = np.arange(1000, dtype=np.int8)\nc = np.arange(1000, dtype=np.int16)\nc += a + b\nprint(c)\n'

In [9]:
# error is resolved by just changing the dtype of 'a' manually
a = np.random.normal(0,1,10)
a = a.astype(np.int16)
b = np.arange(10, dtype=np.int16)
c = np.arange(10, dtype=np.int16)
c += a + b
print(c)

[ 0  2  4  6  8 10 12 14 16 19]


Unlike python list, we can create multi-dimensional arrays using NumPy.

In [10]:
# nested lists result in multi-dimensional arrays
x1 = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(x1)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


For more information and other NumPy operations based on Python list, refer to the [NumPy documentation](http://numpy.org/).

##### Using NumPy routines

When dealing with very large array, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [11]:
# Create a length-10 integer array filled with zeros
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


In [12]:
# Create a 3x5 floating-point array filled with ones
print(np.ones((3, 5), dtype=float))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# Create a 3x5 array filled with 3.14
print(np.full((3, 5), 3.14))

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [14]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [15]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
print(np.random.random((3, 3)))

[[0.58633195 0.75356191 0.45686723]
 [0.77884148 0.43983014 0.62825148]
 [0.97507799 0.95287251 0.89716083]]


In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
print(np.random.normal(0, 1, (3, 3)))

[[ 1.39442885 -0.35259021  0.18459527]
 [ 1.16535701  0.99896443  1.80337278]
 [-0.15816278 -0.93420954 -0.21781708]]


In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
print(np.random.randint(0, 10, (3, 3)))

[[6 9 6]
 [8 3 4]
 [5 2 1]]


In [18]:
# Returns the identity matrix of specific squared size
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


You can always explore the [documentation](http://numpy.org/) for more.

#### 2. Basics of NumPy Array

##### Attributes of NumPy Array

Each NumPy array has the following attributes,

In [19]:
x3 = np.random.randint(10, size=(3, 4, 5))  # Create a 3-D array

print("x3 ndim: ", x3.ndim) # np.ndim yields the number of dimensions 
print("x3 shape:", x3.shape) # np.shape yields the size of each dimension
print("x3 size: ", x3.size) # np.size yields the total size of the array
print("dtype:", x3.dtype) # np.dtype yields the data type of the array
print("itemsize:", x3.itemsize, "bytes") # np.itemsize yields the size (in bytes) of each array element
print("nbytes:", x3.nbytes, "bytes") # np.nbytes yields the total size (in bytes) of the array

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


For more information, refer the [documentation](http://numpy.org/).

##### Accessing elements: Slicing and Indexing

Slicing and Indexing of NumPy Arrays is quite similar to that of Python lists

In [20]:
data = np.arange(10) # Create a 1-D array
print("Original Data:\n", data, "\n")

# Indexing
print("Indexing NumPy Array:")
print("  ", data[4]) # 4th element of the numpy array
print("  ", data[-1], "\n") # 1st element from right side of the numpy array

# Slicing: To access a slice of an array 'data', we use this `data[start:stop:step]`
print("Slicing NumPy Array:")
print("  ", data[:5]) # First 5 element of the numpy array
print("  ", data[::-1]) # All the elements of the numpy array but in reverse order


Original Data:
 [0 1 2 3 4 5 6 7 8 9] 

Indexing NumPy Array:
   4
   9 

Slicing NumPy Array:
   [0 1 2 3 4]
   [9 8 7 6 5 4 3 2 1 0]


<u><i>Indexing in a multi-dimentional NumPy Array</i></u>: Multi-dimensional indices work in the same way, with multiple indices separated by commas

In [21]:
# Let's create a 3-D array
x3 = np.random.randint(10, size=(3, 4, 5))
print(x3)

[[[0 2 7 1 3]
  [3 3 5 1 4]
  [6 8 7 2 5]
  [3 6 5 5 7]]

 [[0 0 9 2 7]
  [7 3 1 1 8]
  [0 6 5 0 3]
  [6 4 9 8 6]]

 [[5 7 7 2 5]
  [6 0 5 7 9]
  [1 5 7 5 6]
  [9 5 0 0 9]]]


In [22]:
print(x3[1]) # prints the 2nd 4x5 array in the generated 3-D array

[[0 0 9 2 7]
 [7 3 1 1 8]
 [0 6 5 0 3]
 [6 4 9 8 6]]


In [23]:
print(x3[1,2]) # prints the 3rd row of the x3[1] array

[0 6 5 0 3]


In [24]:
print(x3[1,2,3]) # prints the 4th element of the x3[1,2] array

0


<u><i>Slicing in a multi-dimentional NumPy Array</i></u>: Multi-dimensional slices work in the same way, with multiple slices separated by commas

In [25]:
# Let's create a 3-D array
x3 = np.random.randint(10, size=(3, 4, 5))
print(x3)

[[[7 0 8 7 5]
  [2 9 7 0 5]
  [9 9 0 0 6]
  [7 6 2 7 9]]

 [[0 0 0 7 0]
  [2 8 0 4 5]
  [0 4 7 5 0]
  [9 0 6 5 3]]

 [[1 7 3 4 1]
  [5 0 7 6 7]
  [0 4 1 0 6]
  [2 9 8 9 9]]]


In [26]:
print(x3[:2, :3, :4])  # prints a 3x4x5 array is sliced into 2x3x4 array

[[[7 0 8 7]
  [2 9 7 0]
  [9 9 0 0]]

 [[0 0 0 7]
  [2 8 0 4]
  [0 4 7 5]]]


<u><i>Mask Indexing and Boolean Slicing</i></u>: These technique are used to filter and get quick inference about the nature of the dataset that we have

In [27]:
# Mask Indexing
numpy_array = np.random.randint(1, 11, size=(10))
print("NumPy Array:\n", numpy_array, "\n")

# Let's create a mask for the 'numpy_array' such that we can filter out the elements that are 'greater than 5'
mask = numpy_array > 5
print("Masked Array:\n", mask, "\n")

# Now let's just print the elements that follow our condition
print("Interested Array:\n", numpy_array[mask])

NumPy Array:
 [3 1 4 1 1 8 1 6 8 9] 

Masked Array:
 [False False False False False  True False  True  True  True] 

Interested Array:
 [8 6 8 9]


For further exploration, refer the [documentation](https://numpy.org/doc/1.17/user/basics.indexing.html) of NumPy

##### Python Lists and NumPy Arrays

NumPy utilizes efficient pointers to a location in memory and it will store the full array. Lists on the other hand are pointers to many different objects in memory.

<u><i>Subarray (default returns)</i></u>: Slicing returns a view for a NumPy Array, where as Python Lists returns a copy the list

In [28]:
# Let's create a NumPy Array and slice it
data_numpy = np.random.randint(10, size=(10))
print("Pre-slicing NumPy Array: ", data_numpy)
slicing_numpy = data_numpy[0:3]
print("Slice of NumPy Array: ", slicing_numpy)

# Let's create a Python List and slice it
import random
data_list = random.sample(range(0, 10), 10)
print("\nPre-slicing Python List: ", data_list)
slicing_list = data_list[0:3]
print("Slice of Python List: ", slicing_list)

Pre-slicing NumPy Array:  [7 4 5 3 8 7 0 4 1 6]
Slice of NumPy Array:  [7 4 5]

Pre-slicing Python List:  [3, 8, 4, 2, 9, 1, 0, 7, 6, 5]
Slice of Python List:  [3, 8, 4]


In [29]:
# Let's change the first element of both array and list
slicing_numpy[0] = -1
print("Slice of NumPy Array: ", slicing_numpy)
slicing_list[0] = -1
print("Slice of Python List: ", slicing_list)

Slice of NumPy Array:  [-1  4  5]
Slice of Python List:  [-1, 8, 4]


In [30]:
print("Post-slicing NumPy array: ", data_numpy) # has changed
print("Post-slicing Python list: ", data_list) # has not changed

Post-slicing NumPy array:  [-1  4  5  3  8  7  0  4  1  6]
Post-slicing Python list:  [3, 8, 4, 2, 9, 1, 0, 7, 6, 5]


<u><i>Subarray (custom)</i></u>: Slicing of NumPy Array should create a copy of the array just like Python Lists

In [31]:
# Creating copies of the array instead of views
data_numpy = np.random.randint(10, size=(10))
print("Pre-slicing NumPy Array: ", data_numpy)
slicing_numpy_copy = data_numpy[0:3].copy()
print("Slice of NumPy Array: ", slicing_numpy_copy)

Pre-slicing NumPy Array:  [4 5 8 0 8 8 7 4 4 9]
Slice of NumPy Array:  [4 5 8]


In [32]:
# Let's chage the first element of our numpy array and observe
slicing_numpy_copy[0] = -1
print("Post-slicing NumPy Array: ", slicing_numpy_copy)
print("Pre-slicing NumPy Array: ", data_numpy) # now it is not a view any more but we created a copy of data_numpy

Post-slicing NumPy Array:  [-1  5  8]
Pre-slicing NumPy Array:  [4 5 8 0 8 8 7 4 4 9]


### Computation 

#### 1. Universal Function
A universal function (or ufunc) that is applied on an `ndarray` in an element-by-element fashion. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

In [34]:
# Let's define two NumPy Arrays
x = np.random.randint(1, 11, size=(10))
y = np.random.randint(1, 11, size=(10))
print ("Array 'x' = ", x)
print ("Array 'y' = ", y)

Array 'x' =  [3 8 3 9 1 2 6 6 6 2]
Array 'y' =  [ 9  8  5  7 10  1  6  6  5  5]


In [35]:
# Let's perform some arithmetic on these arrays
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)  # floor division
print(x % y)

[12 16  8 16 11  3 12 12 11  7]
[-6  0 -2  2 -9  1  0  0  1 -3]
[27 64 15 63 10  2 36 36 30 10]
[0.33333333 1.         0.6        1.28571429 0.1        2.
 1.         1.         1.2        0.4       ]
[0 1 0 1 0 2 1 1 1 0]
[3 0 3 2 1 0 0 0 1 2]


Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy, for example, the `+` operator is a wrapper for the `add` function

In [36]:
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.mod(x, y))

[12 16  8 16 11  3 12 12 11  7]
[-6  0 -2  2 -9  1  0  0  1 -3]
[27 64 15 63 10  2 36 36 30 10]
[3 0 3 2 1 0 0 0 1 2]


The following table lists some of the `ufunc` implemented in NumPy:


| Universal Functions	  | Operator (if any)  | Description                                                    |
|:-----------------------:|:------------------:|:--------------------------------------------------------------:|
|``np.add``               | ``+``              |Addition (e.g., ``[10  6  8] + [3 10  6] = [13 16 14]``)        |
|``np.subtract``          | ``-``              |Subtraction (e.g., ``[10  6  8] - [3 10  6] = [ 7 -4  2]``)     |
|``np.negative``          | ``-``              |Unary negation (e.g., ``[-10  -6  -8]``)                        |
|``np.multiply``          | ``*``              |Multiplication (e.g., ``[10  6  8] * [3 10  6] = [30 60 48]``)  |
|``np.divide``            | ``/``              |Division (e.g., ``[10  6  8] / [3 10  6] = [3.33 0.6 1.33]``)   |
|``np.floor_divide``      | ``//``             |Floor division (e.g., ``[10  6  8] // [3 10  6] = [3 0 1]``)    |
|``np.mod``               | ``%``              |Modulus/remainder (e.g., ``[10  6  8] % [3 10  6] = [1 6 2]``)  |
|``np.log``               |                    |Natural logarithm, element-wise                                 |
|``np.log2``              |                    |Base-2 logarithm of x                                           |


More information on universal functions (including the full list of available functions) can found in the NumPy [documentation](https://numpy.org/doc/1.17/reference/ufuncs.html).

#### 2. NumPy Routines

NumPy being a the scientific computing package, it has several in-build routines/functions to aid mathematical and scientific computing. Some of the common routines used in Machine Learning are discussed below.

In [38]:
# NumPy allows use to concatenate or append different NumPy Arrays
a = np.random.randint(1, 11, size=(3, 3, 2))
b = np.random.randint(1, 11, size=(3, 3, 3))
c = np.ones((1, 3, 2), dtype="int32")
d = np.ones((3, 1, 2), dtype="int32")

print("'a':\n", a, "\n")
print("'b':\n", b, "\n")
print("'c':\n", c, "\n")
print("'d':\n", d, "\n")

# Let's concatenate 'a' and 'b' together alond axis=2
print("Concatenate:\n", np.concatenate((a, b), axis=2), "\n")

# Let's append 'c' to 'a' vertically
print("Vertical Append:\n", np.vstack((a, c)), "\n") # try appending 'd' to 'a' vertically

# Let's append 'd' to 'a' horizontally
print("Horizontal Append:\n", np.hstack((a, d))) # try appending 'c' to 'a' horizontally

'a':
 [[[6 6]
  [4 5]
  [7 9]]

 [[8 2]
  [7 7]
  [9 3]]

 [[1 2]
  [8 5]
  [1 6]]] 

'b':
 [[[ 1 10  3]
  [ 2  4  8]
  [ 5 10  4]]

 [[ 6  7  2]
  [ 2  9  5]
  [ 3  8  5]]

 [[ 8  2  9]
  [ 5  4  7]
  [ 3 10  1]]] 

'c':
 [[[1 1]
  [1 1]
  [1 1]]] 

'd':
 [[[1 1]]

 [[1 1]]

 [[1 1]]] 

Concatenate:
 [[[ 6  6  1 10  3]
  [ 4  5  2  4  8]
  [ 7  9  5 10  4]]

 [[ 8  2  6  7  2]
  [ 7  7  2  9  5]
  [ 9  3  3  8  5]]

 [[ 1  2  8  2  9]
  [ 8  5  5  4  7]
  [ 1  6  3 10  1]]] 

Vertical Append:
 [[[6 6]
  [4 5]
  [7 9]]

 [[8 2]
  [7 7]
  [9 3]]

 [[1 2]
  [8 5]
  [1 6]]

 [[1 1]
  [1 1]
  [1 1]]] 

Horizontal Append:
 [[[6 6]
  [4 5]
  [7 9]
  [1 1]]

 [[8 2]
  [7 7]
  [9 3]
  [1 1]]

 [[1 2]
  [8 5]
  [1 6]
  [1 1]]]


In [39]:
# Let's create a random NumPy Array
numpy_array = np.random.randint(1, 11, size=(9))
print("Original Array Shape: ", numpy_array.shape)
print("Original Array: ", numpy_array, "\n")

# Using np.reshape() routine to reshape an array
numpy_array = numpy_array.reshape(3,3)
print("New Array Shape: ", numpy_array.shape)
print("New Array:\n", numpy_array)

Original Array Shape:  (9,)
Original Array:  [ 6  3 10  6  9 10  9  2  8] 

New Array Shape:  (3, 3)
New Array:
 [[ 6  3 10]
 [ 6  9 10]
 [ 9  2  8]]


In [40]:
# We can also flatten matrices using ravel()
numpy_array = np.random.randint(1, 11, size=(24))
numpy_array = numpy_array.reshape(4,6)
print("Original Array Shape: ", numpy_array.shape)
print("Original Array:\n", numpy_array, "\n")

# Flattening an unflattened array
numpy_array = numpy_array.ravel()
print("Flattened Array Shape: ", numpy_array.shape)
print ("Flattened Array:\n", numpy_array)

Original Array Shape:  (4, 6)
Original Array:
 [[ 2  3  4  7  6 10]
 [ 9  5  5  9 10  4]
 [ 7  1 10  1  4  9]
 [ 9  8  3 10  7  9]] 

Flattened Array Shape:  (24,)
Flattened Array:
 [ 2  3  4  7  6 10  9  5  5  9 10  4  7  1 10  1  4  9  9  8  3 10  7  9]


In [41]:
# Other useful routines for data analysis using NumPy
numpy_array = np.random.randint(1, 11, size=(3, 4))

print(numpy_array, "\n")
print ("Sum of all Elements:", numpy_array.sum())
print("Smallest Element:", numpy_array.min())
print("Highest Element:", numpy_array.max())
print("Cumulative Sum of Elements:", numpy_array.cumsum())
print ("Column-wise Sum:", numpy_array.sum(axis=0))
print ("Row-wise Sum:",numpy_array.sum(axis=1))

[[8 5 3 6]
 [5 5 9 8]
 [7 7 4 1]] 

Sum of all Elements: 68
Smallest Element: 1
Highest Element: 9
Cumulative Sum of Elements: [ 8 13 16 22 27 32 41 49 56 63 67 68]
Column-wise Sum: [20 17 16 15]
Row-wise Sum: [22 27 19]


You can do matrix multiplication and matrix manipulations

In [42]:
# Dot products of two "arrays"
a = np.random.randint(1, 11, size=(3, 3))
b = np.random.randint(1, 11, size=(3, 3))

print("'a':\n", a, "\n")
print("'b':\n", b, "\n")

print("Dot Product of 'a' and 'b' (arrays):\n", np.dot(a, b))

'a':
 [[ 3  7  2]
 [ 8  8  4]
 [ 2 10  3]] 

'b':
 [[7 6 2]
 [7 6 6]
 [7 4 6]] 

Dot Product of 'a' and 'b' (arrays):
 [[ 84  68  60]
 [140 112  88]
 [105  84  82]]


In [43]:
# Matrix product of two "arrays"
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(4, 2))

print("'a':\n", a, "\n")
print("'b':\n", b, "\n")

print("Matrix Product of 'a' and 'b' (arrays):\n", np.matmul(a, b))

'a':
 [[9 7 7 9]
 [4 1 7 5]
 [2 3 2 5]] 

'b':
 [[8 5]
 [7 5]
 [1 3]
 [5 7]] 

Matrix Product of 'a' and 'b' (arrays):
 [[173 164]
 [ 71  81]
 [ 64  66]]


In [44]:
# Taking the transpose of an array Matrix
a = np.random.randint(1, 11, size=(3, 4))
print("'a':\n", a, "\n")

# You can take transpose in two ways
print("'a' Transpose (using 'array.T'):\n", a.T, "\n")
print("'a' Transpose (using 'np.transpose()''):\n", np.transpose(a), "\n")

'a':
 [[ 9  1  5  5]
 [ 1  5 10  7]
 [ 6  8  9  4]] 

'a' Transpose (using 'array.T'):
 [[ 9  1  6]
 [ 1  5  8]
 [ 5 10  9]
 [ 5  7  4]] 

'a' Transpose (using 'np.transpose()''):
 [[ 9  1  6]
 [ 1  5  8]
 [ 5 10  9]
 [ 5  7  4]] 



There so many more routines available in this package. To explore all the NumPy routines, refer the [documentation](https://numpy.org/doc/1.17/reference/routines.html).